/** Admin catalog business management UI (AOP.2) — RU/KK parity. */
export type AdminCatalogLocale = 'ru' | 'kk';

const labels = {
  ru: {
    navCatalog: 'Каталог',
    navBusinesses: 'Заведения',
    pageListTitle: 'Заведения каталога',
    pageCreateTitle: 'Новое заведение',
    pageDetailTitle: 'Карточка заведения',
    createAction: 'Создать заведение',
    loading: 'Загрузка…',
    emptyList: 'Нет заведений по выбранным фильтрам.',
    emptyNoData: 'Заведений пока нет.',
    resetFilters: 'Сбросить фильтры',
    searchLabel: 'Поиск по названию',
    colActions: 'Действия',
    errorLoad: 'Не удалось загрузить список.',
    filterStatus: 'Статус',
    filterAll: 'Все',
    colTitle: 'Название',
    colStatus: 'Статус',
    colCity: 'Город (основной филиал)',
    colCategory: 'Категория',
    colSlug: 'Slug',
    openDetail: 'Открыть',
    sectionCore: 'Основные данные',
    sectionTaxonomy: 'Таксономия',
    sectionLifecycle: 'Публикация',
    sectionLocations: 'Филиалы',
    sectionCatalogEdit: 'Редактирование каталога',
    primaryBranchHint: 'Первый филиал будет основным (PRIMARY).',
    primaryBadge: 'Основной',
    addLocation: 'Добавить филиал',
    editLocation: 'Редактировать',
    makePrimary: 'Сделать основным',
    deleteLocation: 'Удалить филиал',
    confirmDeleteLocation: 'Удалить этот филиал? Это действие необратимо.',
    locationSaved: 'Филиал сохранён.',
    cancel: 'Отмена',
    fieldLocationSource: 'Источник координат',
    noOwner: 'Без владельца',
    ownerAttached: 'Владелец назначен',
    saveCatalog: 'Сохранить изменения',
    saving: 'Сохранение…',
    createSubmit: 'Создать',
    creating: 'Создание…',
    successCreated: 'Заведение создано.',
    slugReadOnly: 'Slug (не изменяется)',
    fieldTitle: 'Название',
    fieldSlug: 'Slug',
    fieldCategory: 'Категория',
    fieldSubcategories: 'Подкатегории',
    fieldShortDesc: 'Краткое описание',
    fieldDescription: 'Описание',
    fieldAddress: 'Адрес основного филиала',
    fieldCity: 'Город',
    fieldPhone: 'Телефон',
    fieldWhatsapp: 'WhatsApp',
    fieldInstagram: 'Instagram',
    fieldWebsite: 'Сайт',
    fieldWorkHours: 'Часы работы (JSON)',
    fieldLat: 'Широта',
    fieldLng: 'Долгота',
    errDuplicateSlug: 'Такой slug уже занят.',
    errForbidden: 'Недостаточно прав для этого действия.',
    errUnauthorized: 'Сессия истекла. Войдите снова.',
    errValidation: 'Проверьте поля формы.',
    errNetwork: 'Ошибка сети или сервера.',
    errGeneric: 'Операция не выполнена.',
    localeRu: 'RU',
    localeKk: 'KK',
    linkContent: 'Контент и акции',
    sectionTeam: 'Менеджеры заведения',
    linkTeam: 'Управление командой',
    pageTeamTitle: 'Команда заведения',
    teamPanelHint:
      'Администрирование менеджеров заведения (OWNER → MANAGER). Владельцы по-прежнему управляют командой в Business Web.',
    teamFeatureUnavailableTitle: 'Раздел временно недоступен',
    teamFeatureUnavailableHint:
      'Управление менеджерами заведения в Admin Web отключено. Включите NEXT_PUBLIC_QALAGO_ADMIN_BUSINESS_TEAM=true для разработки.',
    statusPending: 'На модерации',
    statusActive: 'Активно',
    statusBlocked: 'Заблокировано',
    actionActivate: 'Опубликовать (ACTIVE)',
    actionBlock: 'Заблокировать',
    confirmActivate: 'Опубликовать заведение в каталоге?',
    confirmBlock: 'Заблокировать заведение? Оно исчезнет из публичного каталога.',
    saveTaxonomy: 'Сохранить таксономию',
    taxonomySaved: 'Таксономия обновлена.',
  },
  kk: {
    navCatalog: 'Каталог',
    navBusinesses: 'Заведения',
    pageListTitle: 'Каталог заведениялары',
    pageCreateTitle: 'Жаңа заведение',
    pageDetailTitle: 'Заведение карточкасы',
    createAction: 'Заведение құру',
    loading: 'Жүктелуде…',
    emptyList: 'Сүзгілер бойынша заведение жоқ.',
    emptyNoData: 'Заведение әлі жоқ.',
    resetFilters: 'Сүзгілерді тастау',
    searchLabel: 'Атау бойынша іздеу',
    colActions: 'Әрекеттер',
    errorLoad: 'Тізімді жүктеу сәтсіз.',
    filterStatus: 'Мәртебе',
    filterAll: 'Барлығы',
    colTitle: 'Атауы',
    colStatus: 'Мәртебе',
    colCity: 'Қала (негізгі филиал)',
    colCategory: 'Санат',
    colSlug: 'Slug',
    openDetail: 'Ашу',
    sectionCore: 'Негізгі деректер',
    sectionTaxonomy: 'Таксономия',
    sectionLifecycle: 'Жариялау',
    sectionLocations: 'Филиалдар',
    sectionCatalogEdit: 'Каталогты өңдеу',
    primaryBranchHint: 'Бірінші филиал негізгі (PRIMARY) болады.',
    primaryBadge: 'Негізгі',
    addLocation: 'Филиал қосу',
    editLocation: 'Өңдеу',
    makePrimary: 'Негізгі ету',
    deleteLocation: 'Филиалды жою',
    confirmDeleteLocation: 'Бұл филиалды жою керек пе? Бұл қайтымсыз.',
    locationSaved: 'Филиал сақталды.',
    cancel: 'Болдырмау',
    fieldLocationSource: 'Координат көзі',
    noOwner: 'Иесіз',
    ownerAttached: 'Иесі бар',
    saveCatalog: 'Өзгерістерді сақтау',
    saving: 'Сақталуда…',
    createSubmit: 'Құру',
    creating: 'Құрылуда…',
    successCreated: 'Заведение құрылды.',
    slugReadOnly: 'Slug (өзгертілмейді)',
    fieldTitle: 'Атауы',
    fieldSlug: 'Slug',
    fieldCategory: 'Санат',
    fieldSubcategories: 'Ішкі санаттар',
    fieldShortDesc: 'Қысқаша сипаттама',
    fieldDescription: 'Сипаттама',
    fieldAddress: 'Негізгі филиал мекенжайы',
    fieldCity: 'Қала',
    fieldPhone: 'Телефон',
    fieldWhatsapp: 'WhatsApp',
    fieldInstagram: 'Instagram',
    fieldWebsite: 'Сайт',
    fieldWorkHours: 'Жұмыс уақыты (JSON)',
    fieldLat: 'Ендік',
    fieldLng: 'Бoyлық',
    errDuplicateSlug: 'Мұндай slug бос емес.',
    errForbidden: 'Бұл әрекет үшін құқық жеткіліксіз.',
    errUnauthorized: 'Сессия аяқталды. Қайта кіріңіз.',
    errValidation: 'Форма өрістерін тексеріңіз.',
    errNetwork: 'Желі немесе сервер қатесі.',
    errGeneric: 'Операция орындалмады.',
    localeRu: 'RU',
    localeKk: 'KK',
    linkContent: 'Контент пен акциялар',
    sectionTeam: 'Заведение менеджерлері',
    linkTeam: 'Команданы басқару',
    pageTeamTitle: 'Заведение командасы',
    teamPanelHint:
      'Заведение менеджерлерін әкімшілік (OWNER → MANAGER). Иелер командасын Business Web арқылы басқара береді.',
    teamFeatureUnavailableTitle: 'Бөлім уақытша қолжетімсіз',
    teamFeatureUnavailableHint:
      'Admin Web-те менеджерлерді басқару өшірілген. Әзірлеу үшін NEXT_PUBLIC_QALAGO_ADMIN_BUSINESS_TEAM=true қойыңыз.',
    statusPending: 'Модерацияда',
    statusActive: 'Белсенді',
    statusBlocked: 'Блокталған',
    actionActivate: 'Жариялау (ACTIVE)',
    actionBlock: 'Блоктау',
    confirmActivate: 'Заведениені каталогта жариялау керек пе?',
    confirmBlock: 'Заведениені блоктау керек пе? Ол жария каталогтан жойылады.',
    saveTaxonomy: 'Таксономияны сақтау',
    taxonomySaved: 'Таксономия жаңартылды.',
  },
} as const;

export type AdminCatalogLabelKey = keyof (typeof labels)['ru'];

export function adminCatalogLabel(locale: AdminCatalogLocale, key: AdminCatalogLabelKey): string {
  return labels[locale][key];
}

export function adminCatalogStatusLabel(locale: AdminCatalogLocale, status: string): string {
  switch (status) {
    case 'PENDING':
      return adminCatalogLabel(locale, 'statusPending');
    case 'ACTIVE':
      return adminCatalogLabel(locale, 'statusActive');
    case 'BLOCKED':
      return adminCatalogLabel(locale, 'statusBlocked');
    default:
      return status;
  }
}

/** Every RU key must exist in KK (parity gate for tests). */
export function adminCatalogLabelKeys(): AdminCatalogLabelKey[] {
  return Object.keys(labels.ru) as AdminCatalogLabelKey[];
}
