import type { BackofficeStatusPresentation } from '@qalago/brand/status';

const AUDIT_ACTION_LABELS: Record<string, string> = {
  TEAM_INVITE: 'Приглашение в команду',
  TEAM_INVITATION_ACCEPT: 'Принятие приглашения',
  TEAM_PERMISSION_UPDATE: 'Изменение прав команды',
  TEAM_SUSPEND: 'Приостановка доступа',
  TEAM_RESTORE: 'Восстановление доступа',
  TEAM_REVOKE: 'Отзыв доступа',
  BUSINESS_CREATE: 'Создание заведения',
  BUSINESS_PROFILE_UPDATE: 'Обновление профиля заведения',
  BUSINESS_TAXONOMY_UPDATE: 'Обновление категории заведения',
  BUSINESS_STATUS_UPDATE: 'Изменение статуса заведения',
  BUSINESS_FEATURED_UPDATE: 'Изменение VIP / Топ',
  BUSINESS_LOCATION_CREATE: 'Создание филиала',
  BUSINESS_LOCATION_UPDATE: 'Обновление филиала',
  BUSINESS_LOCATION_SET_PRIMARY: 'Назначение основного филиала',
  BUSINESS_LOCATION_DELETE: 'Удаление филиала',
  BUSINESS_HOURS_UPDATE: 'Обновление часов работы',
  CATALOG_ITEM_CREATE: 'Создание позиции меню',
  CATALOG_ITEM_UPDATE: 'Изменение позиции меню',
  CATALOG_ITEM_DELETE: 'Удаление позиции меню',
  CATALOG_SECTION_CREATE: 'Создание раздела меню',
  CATALOG_SECTION_UPDATE: 'Изменение раздела меню',
  CATALOG_SECTION_DELETE: 'Удаление раздела меню',
  BUSINESS_PHOTO_ADD: 'Добавление фото',
  BUSINESS_PHOTO_DELETE: 'Удаление фото',
  BUSINESS_COVER_CHANGE: 'Смена обложки',
  PROMOTION_CREATE: 'Создание акции',
  PROMOTION_UPDATE: 'Изменение акции',
  PROMOTION_DELETE: 'Удаление акции',
  REVIEW_REPLY_CREATE: 'Ответ на отзыв',
  REVIEW_CREATE: 'Создание отзыва',
  REVIEW_UPDATE: 'Изменение отзыва',
  REVIEW_DELETE: 'Удаление отзыва',
  REVIEW_RESTORE: 'Восстановление отзыва',
  PLAN_CHECKOUT: 'Оформление тарифа',
  PLAN_OVERRIDE: 'Изменение тарифа (админ)',
  AD_ORDER_CREATE: 'Создание рекламного заказа',
  AD_CREATIVE_CREATE: 'Загрузка рекламного баннера',
  AD_CREATIVE_APPROVE: 'Одобрение баннера',
  AD_CREATIVE_REJECT: 'Отклонение баннера',
  AD_CAMPAIGN_PAUSE: 'Пауза рекламной кампании',
  AD_CAMPAIGN_ACTIVATE: 'Запуск рекламной кампании',
  PAYMENT_CONFIRM: 'Подтверждение оплаты',
  USER_ROLE_CHANGE: 'Смена роли пользователя',
  CITY_CREATE: 'Создание города',
  CITY_UPDATE: 'Обновление города',
  CITY_LAUNCH_STATUS_CHANGE: 'Изменение статуса запуска города',
  CATEGORY_CREATE: 'Создание категории',
  CATEGORY_UPDATE: 'Изменение категории',
  CATEGORY_DELETE: 'Удаление категории',
  BUSINESS_APPLICATION_SUBMIT: 'Подана заявка на заведение',
  BUSINESS_APPLICATION_APPROVE: 'Заявка на заведение одобрена',
  BUSINESS_APPLICATION_REJECT: 'Заявка на заведение отклонена',
  BUSINESS_APPLICATION_CANCEL: 'Заявка на заведение отменена',
  BUSINESS_OWNERSHIP_CLAIM_SUBMIT: 'Подана заявка на владение',
  BUSINESS_OWNERSHIP_CLAIM_APPROVE: 'Заявка на владение одобрена',
  BUSINESS_OWNERSHIP_CLAIM_REJECT: 'Заявка на владение отклонена',
  BUSINESS_OWNERSHIP_CLAIM_CANCEL: 'Заявка на владение отменена',
  RELEASE_CONFIG_UPDATE: 'Обновление release config',
  LEGAL_DOCUMENT_CREATE: 'Создание legal-документа',
  LEGAL_DOCUMENT_PUBLISH: 'Публикация legal-документа',
  LEGAL_DOCUMENT_ARCHIVE: 'Архивация legal-документа',
  DATA_REQUEST_STATUS_CHANGE: 'Изменение статуса data request',
  MODERATION_CASE_ASSIGN: 'Назначение кейса модерации',
  MODERATION_ACTION_APPLY: 'Действие модерации',
  MODERATION_ACTION_RESTORE: 'Отмена модерационного действия',
  MODERATION_APPEAL_DECIDE: 'Решение по апелляции',
  GOVERNMENT_REQUEST_UPDATE: 'Обновление запроса госоргана',
  SECURITY_INCIDENT_UPDATE: 'Обновление инцидента безопасности',
  ACCOUNT_DELETION_EXECUTE: 'Удаление аккаунта',
  STAFF_CREATED: 'Создание staff',
  STAFF_DISABLED: 'Отключение staff',
  STAFF_RESTORED: 'Восстановление staff',
  STAFF_ROLE_CHANGED: 'Смена роли staff',
  STAFF_CITY_SCOPE_CHANGED: 'Изменение scope городов staff',
  STAFF_SESSION_REVOKED: 'Отзыв сессий staff',
  SUPER_ADMIN_ASSIGNED: 'Назначение суперадминистратора',
  ADMIN_ASSIGNED: 'Назначение администратора',
  STAFF_BOOTSTRAP: 'Bootstrap staff',
  STAFF_STEP_UP_VERIFIED: 'Step-up подтверждён',
  STAFF_MFA_ENROLL_STARTED: 'Старт MFA',
  STAFF_MFA_ENABLED: 'MFA включена',
  STAFF_MFA_VERIFIED: 'MFA подтверждена',
  STAFF_MFA_RECOVERY_CODE_USED: 'Использован recovery-код MFA',
  STAFF_MFA_RECOVERY_CODES_REGENERATED: 'Recovery-коды MFA перегенерированы',
  STAFF_MFA_DISABLED: 'MFA отключена',
  STAFF_MFA_RESET: 'Сброс MFA',
  STAFF_MFA_EMERGENCY_RESET: 'Аварийный сброс MFA',
  STAFF_MFA_VERIFICATION_FAILED: 'Неудачная проверка MFA',
};

const UNKNOWN_LABEL = 'Неизвестное действие';

export function auditActionLabel(action: string): string {
  return AUDIT_ACTION_LABELS[action] ?? UNKNOWN_LABEL;
}

export function auditActionPresentation(action: string): BackofficeStatusPresentation {
  return { label: auditActionLabel(action), tone: 'info' };
}

export function auditActionFilterLabel(action: string): string {
  return auditActionLabel(action);
}
