export const MAX_REPORT_DETAILS_LENGTH = 2000;
export const MAX_APPEAL_REASON_LENGTH = 2000;
export const MAX_MODERATOR_NOTE_LENGTH = 4000;
export const MAX_LEGAL_CONTENT_LENGTH = 200_000;

export const SAFETY_REPORT_IP_LIMIT = 10;
export const SAFETY_REPORT_IP_WINDOW_SECONDS = 900;
export const SAFETY_APPEAL_USER_LIMIT = 5;
export const SAFETY_APPEAL_USER_WINDOW_SECONDS = 86400;
export const SAFETY_DATA_RIGHTS_USER_LIMIT = 3;
export const SAFETY_DATA_RIGHTS_USER_WINDOW_SECONDS = 86400;
