export const SafetyErrorCode = {
  REPORT_ALREADY_SUBMITTED: 'REPORT_ALREADY_SUBMITTED',
  CONTENT_NOT_REPORTABLE: 'CONTENT_NOT_REPORTABLE',
  APPEAL_ALREADY_SUBMITTED: 'APPEAL_ALREADY_SUBMITTED',
  APPEAL_NOT_ALLOWED: 'APPEAL_NOT_ALLOWED',
  BUSINESS_OWNERSHIP_REQUIRES_RESOLUTION: 'BUSINESS_OWNERSHIP_REQUIRES_RESOLUTION',
  DATA_REQUEST_ALREADY_ACTIVE: 'DATA_REQUEST_ALREADY_ACTIVE',
  ACCOUNT_RESTRICTED: 'ACCOUNT_RESTRICTED',
} as const;

export type SafetyErrorCode = (typeof SafetyErrorCode)[keyof typeof SafetyErrorCode];
