export const SafetyErrorCode = {
  REPORT_ALREADY_SUBMITTED: 'REPORT_ALREADY_SUBMITTED',
  CONTENT_NOT_REPORTABLE: 'CONTENT_NOT_REPORTABLE',
  MODERATION_NOTE_REQUIRED: 'MODERATION_NOTE_REQUIRED',
  APPEAL_ALREADY_SUBMITTED: 'APPEAL_ALREADY_SUBMITTED',
  APPEAL_NOT_ALLOWED: 'APPEAL_NOT_ALLOWED',
  BUSINESS_OWNERSHIP_REQUIRES_RESOLUTION: 'BUSINESS_OWNERSHIP_REQUIRES_RESOLUTION',
  DATA_REQUEST_ALREADY_ACTIVE: 'DATA_REQUEST_ALREADY_ACTIVE',
  ACCOUNT_RESTRICTED: 'ACCOUNT_RESTRICTED',
  LEGAL_ACCEPTANCE_REQUIRED: 'LEGAL_ACCEPTANCE_REQUIRED',
  LEGAL_VERSION_STALE: 'LEGAL_VERSION_STALE',
  LEGAL_DOCUMENT_NOT_FOUND: 'LEGAL_DOCUMENT_NOT_FOUND',
} as const;

export type SafetyErrorCode = (typeof SafetyErrorCode)[keyof typeof SafetyErrorCode];
