-- Stage 5N.2: AuditAction values for business ownership claim flow

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BUSINESS_OWNERSHIP_CLAIM_SUBMIT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BUSINESS_OWNERSHIP_CLAIM_APPROVE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BUSINESS_OWNERSHIP_CLAIM_REJECT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BUSINESS_OWNERSHIP_CLAIM_CANCEL';

ALTER TYPE "AuditResourceType" ADD VALUE IF NOT EXISTS 'BUSINESS_OWNERSHIP_CLAIM';
