-- Stage 5N.1: AuditAction values for business application flow

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BUSINESS_APPLICATION_SUBMIT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BUSINESS_APPLICATION_APPROVE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BUSINESS_APPLICATION_REJECT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BUSINESS_APPLICATION_CANCEL';

ALTER TYPE "AuditResourceType" ADD VALUE IF NOT EXISTS 'BUSINESS_APPLICATION';
