-- AOP.5 — Admin catalog privileged mutation audit actions (additive enum only)
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BUSINESS_TAXONOMY_UPDATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BUSINESS_STATUS_UPDATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BUSINESS_FEATURED_UPDATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BUSINESS_LOCATION_CREATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BUSINESS_LOCATION_UPDATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BUSINESS_LOCATION_SET_PRIMARY';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BUSINESS_LOCATION_DELETE';
