-- Stage 6.11D.2: review soft delete and lifecycle audit actions.

ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'REVIEW_CREATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'REVIEW_UPDATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'REVIEW_DELETE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'REVIEW_RESTORE';
