-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'REVIEW_HIDDEN';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'REVIEW_RESTORED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'BUSINESS_APPLICATION_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'BUSINESS_APPLICATION_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'OWNERSHIP_CLAIM_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'OWNERSHIP_CLAIM_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'BUSINESS_INVITATION_RECEIVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'BUSINESS_INVITATION_ACCEPTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'AD_CAMPAIGN_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'AD_CAMPAIGN_REJECTED';
